import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, rm, symlink, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { parsePackageVersion, parseSdkRequirements } from './generate-terraform-docs.ts';
import { SourceTree } from './source-tree.ts';
import {
  buildTerraformDocs,
  declarationFiles,
  parseDeclarationMarkdown,
  parseSdkApiMarkdown,
  parseServiceSource,
} from './terraform-provider.ts';

const API_MD = `
## Widgets
- <code title="post /accounts/{account_id}/widgets">client.Widgets.<a href="https://pkg.go.dev/github.com/cloudflare/cloudflare-go/v7/widgets#WidgetService.New">New</a>(ctx <a href="https://pkg.go.dev/context">context</a>.<a href="https://pkg.go.dev/context#Context">Context</a>) (\\*widgets.Widget, error)</code>
- <code title="get /accounts/{account_id}/widgets/{widget_id}">client.Widgets.<a href="https://pkg.go.dev/x#WidgetService.Get">Get</a>(ctx, widgetID) (\\*widgets.Widget, error)</code>
- <code title="get /accounts/{account_id}/widgets">client.Widgets.<a href="https://pkg.go.dev/x#WidgetService.List">List</a>(ctx) (\\*pagination.Page, error)</code>
- <code title="delete /accounts/{account_id}/widgets/{widget_id}">client.Widgets.<a href="https://pkg.go.dev/x#WidgetService.Delete">Delete</a>(ctx, widgetID) error</code>
`;

const RESOURCE_GO = `package widget

import (
	"github.com/cloudflare/cloudflare-go/v7"
	"github.com/cloudflare/cloudflare-go/v7/option"
)

func (r *WidgetResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_widget"
}

func (r *WidgetResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	_, err = r.client.Widgets.New(ctx, option.WithRequestBody("application/json", dataBytes))
}

func (r *WidgetResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	_, err := r.client.Widgets.Get(ctx, data.ID.ValueString())
}

func (r *WidgetResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	_, err := r.client.Widgets.Delete(ctx, data.ID.ValueString())
}

func (r *WidgetResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	_, err := r.client.Widgets.Get(ctx, path_widget_id)
}
`;

const LIST_GO = `package widget
import "github.com/cloudflare/cloudflare-go/v7"
func (d *WidgetsDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_widgets"
}
func (d *WidgetsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	page, err := d.client.Widgets.ListAutoPaging(ctx, params)
	other := d.client.Widgets.Rename(ctx)
}
`;

const WIDGET_MD = `---
page_title: "cloudflare_widget Resource - Cloudflare"
subcategory: ""
description: |-
  Manages a widget.
---

# cloudflare_widget (Resource)

Manages a widget.

- \`Widget Write\`

## Example Usage

\`\`\`terraform
resource "cloudflare_widget" "example" {}
\`\`\`

<!-- schema generated by tfplugindocs -->
## Schema

### Required

- \`name\` (String) Widget name.
Available values: "a", "b".
- \`account_id\` (String)

### Optional

- \`secret\` (String, Sensitive) A secret.
- \`token\` (String, Sensitive, [Write-only](https://developer.hashicorp.com/terraform/language/resources/ephemeral#write-only-arguments)) Write-only token.
- \`settings\` (Attributes) Widget settings. (see [below for nested schema](#nestedatt--settings))

### Read-Only

- \`id\` (String) The ID of this resource.
- \`tags\` (List of String)

<a id="nestedatt--settings"></a>
### Nested Schema for \`settings\`

Optional:

- \`mode\` (Attributes) Mode. (see [below for nested schema](#nestedatt--settings--mode))

Read-Only:

- \`enabled\` (Boolean, Deprecated) Whether it is enabled.

<a id="nestedatt--settings--mode"></a>
### Nested Schema for \`settings.mode\`

Required:

- \`value\` (Number)

## Import

\`\`\`shell
$ terraform import cloudflare_widget.example '<id>'
\`\`\`
`;

const WIDGETS_MD = `# cloudflare_widgets (Data Source)

<!-- schema generated by tfplugindocs -->
## Schema

### Required

- \`account_id\` (String)
`;

test('parseSdkApiMarkdown maps SDK accessors to documented endpoints', () => {
  const endpoints = parseSdkApiMarkdown(API_MD);
  assert.equal(endpoints.get('Widgets.New'), 'post /accounts/{account_id}/widgets');
  assert.equal(endpoints.get('Widgets.Delete'), 'delete /accounts/{account_id}/widgets/{widget_id}');
  assert.equal(endpoints.size, 4);
});

test('parseServiceSource records the type name, SDK module and lifecycle role of each call', () => {
  const resource = parseServiceSource(RESOURCE_GO, 'resource');
  assert.equal(resource?.name, 'cloudflare_widget');
  assert.equal(resource?.sdkModule, 'github.com/cloudflare/cloudflare-go/v7');
  assert.deepEqual(resource?.calls, [
    { call: 'Widgets.New', role: 'create' },
    { call: 'Widgets.Get', role: 'read' },
    { call: 'Widgets.Delete', role: 'delete' },
    { call: 'Widgets.Get', role: 'import' },
  ]);
  const list = parseServiceSource(LIST_GO, 'list-data-source');
  assert.deepEqual(list?.calls[0], { call: 'Widgets.List', role: 'read' });
  assert.equal(parseServiceSource('package nothing', 'resource'), undefined);
});

test('parseDeclarationMarkdown reads tfplugindocs groups, flags and nested schemas', () => {
  const doc = parseDeclarationMarkdown(WIDGET_MD, 'docs/resources/widget.md');
  assert.equal(doc.name, 'cloudflare_widget');
  assert.equal(doc.description, 'Manages a widget.\n\n- `Widget Write`');
  assert.deepEqual(doc.required, [
    { name: 'account_id', type: 'String' },
    { name: 'name', type: 'String', description: 'Widget name.\nAvailable values: "a", "b".' },
  ]);
  assert.deepEqual(
    doc.optional.map(({ name, sensitive }) => [name, sensitive ?? false]),
    [
      ['secret', true],
      ['settings', false],
      ['token', true],
    ],
  );
  assert.deepEqual(doc.optional[1], {
    name: 'settings',
    type: 'Attributes',
    description: 'Widget settings.',
    children: [
      { name: 'enabled', type: 'Boolean', description: 'Whether it is enabled.', deprecated: 'Deprecated.' },
      { name: 'mode', type: 'Attributes', description: 'Mode.', children: [{ name: 'value', type: 'Number' }] },
    ],
  });
  assert.deepEqual(
    doc.computed.map(({ name, type }) => [name, type]),
    [
      ['id', 'String'],
      ['tags', 'List of String'],
    ],
  );
});

test('parseDeclarationMarkdown fails with file:line on anything unexpected', () => {
  const file = 'docs/resources/widget.md';
  const lineOf = (needle) => WIDGET_MD.split('\n').findIndex((line) => line.includes(needle)) + 1;
  const cases = [
    [WIDGET_MD.replace('(String, Sensitive) A secret', '(String, Secret) A secret'), /unknown attribute flag "Secret"/],
    [WIDGET_MD.replace('(#nestedatt--settings--mode)', '(#nestedatt--nope)'), /references missing nested schema/],
    [WIDGET_MD.replace('<!-- schema generated by tfplugindocs -->', ''), /missing `<!-- schema generated/],
    [WIDGET_MD.replace('### Optional\n\n', '### Optional\n\nSome prose\n'), /unexpected line in schema/],
    [WIDGET_MD.replace('Optional:\n\n- `mode`', '### Optional\n\n- `mode`'), /`### Optional` inside a nested schema/],
    [
      WIDGET_MD.replace(' (see [below for nested schema](#nestedatt--settings--mode))', ''),
      /#nestedatt--settings--mode is not referenced/,
    ],
  ];
  for (const [markdown, message] of cases) {
    assert.throws(() => parseDeclarationMarkdown(markdown, file), message);
  }
  assert.throws(
    () =>
      parseDeclarationMarkdown(WIDGET_MD.replace('(String, Sensitive) A secret', '(String, Secret) A secret'), file),
    new RegExp(`^Error: ${file}:${lineOf('`secret`')}: unknown attribute flag`),
  );
});

test('buildTerraformDocs links declarations to endpoints by role and reports gaps', () => {
  const module = 'github.com/cloudflare/cloudflare-go/v7';
  const files = {
    'docs/resources/widget.md': WIDGET_MD,
    'docs/data-sources/widgets.md': WIDGETS_MD,
    'examples/resources/cloudflare_widget/resource.tf': 'resource "cloudflare_widget" "example" {}\n',
    'examples/resources/cloudflare_widget/import.sh': "$ terraform import cloudflare_widget.example '<id>'\n",
  };
  const docs = buildTerraformDocs({
    provider: { repository: 'https://example.com/provider', version: '1.2.3' },
    sdks: [{ module, version: 'v7.0.0' }],
    services: [
      parseServiceSource(RESOURCE_GO, 'resource'),
      parseServiceSource(LIST_GO, 'list-data-source'),
      { kind: 'resource', name: 'cloudflare_unreleased', sdkModule: module, calls: [] },
    ],
    sdkEndpoints: new Map([[module, parseSdkApiMarkdown(API_MD)]]),
    readProviderFile: (file) => files[file],
  });

  assert.deepEqual(Object.keys(docs.declarations), [
    'resource:cloudflare_widget',
    'list-data-source:cloudflare_widgets',
  ]);
  assert.equal(docs.declarations['resource:cloudflare_widget'].example, 'resource "cloudflare_widget" "example" {}');
  assert.deepEqual(docs.undocumented, ['resource:cloudflare_unreleased']);
  assert.deepEqual(docs.endpoints['get /accounts/{account_id}/widgets/{widget_id}'], [
    { declaration: 'resource:cloudflare_widget', roles: ['read', 'import'] },
  ]);
  assert.deepEqual(docs.endpoints['get /accounts/{account_id}/widgets'], [
    { declaration: 'list-data-source:cloudflare_widgets', roles: ['read'] },
  ]);
  assert.deepEqual(docs.unresolvedCalls, [
    { declaration: 'list-data-source:cloudflare_widgets', call: `${module} Widgets.Rename` },
  ]);
  assert.deepEqual(docs.stats, { declarations: 2, linkedDeclarations: 2, endpoints: 4, unresolvedCalls: 1 });
  assert.throws(
    () =>
      buildTerraformDocs({
        provider: { repository: 'https://example.com/provider', version: '1.2.3' },
        sdks: [],
        services: [parseServiceSource(RESOURCE_GO, 'resource')],
        sdkEndpoints: new Map(),
        readProviderFile: (file) => (file === 'docs/resources/widget.md' ? WIDGETS_MD : undefined),
      }),
    /documents cloudflare_widgets, expected cloudflare_widget/,
  );
});

test('declarationFiles follows the tfplugindocs layout', () => {
  assert.deepEqual(declarationFiles('resource', 'cloudflare_dns_record'), {
    doc: 'docs/resources/dns_record.md',
    example: 'examples/resources/cloudflare_dns_record/resource.tf',
    importExample: 'examples/resources/cloudflare_dns_record/import.sh',
  });
  assert.equal(declarationFiles('list-data-source', 'cloudflare_dns_records').doc, 'docs/data-sources/dns_records.md');
});

test('versions come from go.mod and release-please version files', () => {
  const requirements = parseSdkRequirements(`module x
require (
	github.com/cloudflare/cloudflare-go v0.118.0
	github.com/cloudflare/cloudflare-go/v6 v6.10.0
	github.com/cloudflare/cloudflare-go/v7 v7.12.1-0.20261001120000-0123456789ab
)`);
  assert.deepEqual(
    [...requirements],
    [
      ['github.com/cloudflare/cloudflare-go/v6', 'v6.10.0'],
      ['github.com/cloudflare/cloudflare-go/v7', 'v7.12.1-0.20261001120000-0123456789ab'],
    ],
  );
  assert.equal(
    parsePackageVersion('package internal\n\nconst PackageVersion = "5.27.0" // x-release-please-version\n', 'p'),
    '5.27.0',
  );
  assert.throws(() => parsePackageVersion('package internal', 'provider'), /provider: internal\/version.go/);
});

test('SourceTree confines reads to the checkout and never follows symbolic links', async (t) => {
  const base = await mkdtemp(path.join(os.tmpdir(), 'source-tree-'));
  t.after(() => rm(base, { recursive: true, force: true }));
  const root = path.join(base, 'checkout');
  const secret = path.join(base, 'secret.txt');
  await mkdir(path.join(root, 'examples', 'nested'), { recursive: true });
  await mkdir(path.join(root, '.git'), { recursive: true });
  await writeFile(secret, 'TOP SECRET');
  await writeFile(path.join(root, 'examples', 'nested', 'resource.tf'), 'resource "x" "y" {}');
  await writeFile(path.join(root, 'big.txt'), 'x'.repeat(100));
  await symlink(secret, path.join(root, 'examples', 'leak.tf'));
  await symlink(base, path.join(root, 'examples', 'escape'));
  await writeFile(path.join(root, '.git', 'HEAD'), `${'a'.repeat(40)}\n`);

  const tree = await SourceTree.open('fixture', root);
  assert.equal(await tree.readText('examples/nested/resource.tf'), 'resource "x" "y" {}');
  assert.equal(await tree.readText('examples/missing.tf'), undefined);
  await assert.rejects(tree.readText('examples/leak.tf'), /is a symbolic link/);
  await assert.rejects(tree.readText('examples/escape/secret.txt'), /resolves outside the checkout/);
  await assert.rejects(tree.readText('../secret.txt'), /unsafe path/);
  await assert.rejects(tree.readText(secret), /unsafe path/);
  await assert.rejects(tree.readText('big.txt', 10), /limit 10/);
  assert.deepEqual(await tree.listFiles('examples', () => true), ['examples/nested/resource.tf']);
  assert.equal(await tree.gitCommit(), 'a'.repeat(40));
});

test('the generator scripts stay offline and never spawn processes', async () => {
  for (const file of ['generate-terraform-docs.ts', 'terraform-provider.ts', 'source-tree.ts']) {
    const source = await readFile(new URL(`./${file}`, import.meta.url), 'utf8');
    assert.doesNotMatch(source, /node:(?:child_process|http|https|net|dgram|worker_threads|vm)\b/, file);
    assert.doesNotMatch(source, /\bfetch\(|\beval\(|new Function\(|\bimport\(/, file);
  }
});
